Fix NoMethodError: undefined method `values' for nil:NilClass
when calling `respond_to?` on a Enumerize::Value that has been changed to invalid value.